[package]
name = "kernel_extraction"
version = "0.1.0"
authors = ["Lucas Tepper <lucas.tepper.91@gmail.com>"]
edition = "2021"

[lib]
name = "kernel_extraction"
crate-type = ["cdylib"]

[dependencies]

[dependencies.pyo3]
version = "0.14"
features = ["extension-module"]
